"""Add user in model GraduationProject

Revision ID: 07af3f3cd9a7
Revises: 59f36d9b9219
Create Date: 2022-11-30 02:51:13.842209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07af3f3cd9a7'
down_revision = '59f36d9b9219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
