"""Add rel

Revision ID: 0f39b4586b05
Revises: 4e607d04244c
Create Date: 2022-11-08 22:19:23.788760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f39b4586b05'
down_revision = '4e607d04244c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
