"""fixes v4

Revision ID: 447ed61859ee
Revises: a0fb2f94a285
Create Date: 2022-11-20 15:11:00.925979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447ed61859ee'
down_revision = 'a0fb2f94a285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
