"""Add course project model and diplome

Revision ID: 4e607d04244c
Revises: 52e95c474c12
Create Date: 2022-11-08 20:36:18.673776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e607d04244c'
down_revision = '52e95c474c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_project_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('user_student_id', sa.Integer(), nullable=True),
    sa.Column('percent_of_completion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['user_student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_project_base_id'), 'course_project_base', ['id'], unique=True)
    op.create_table('course_proj_user_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_teacher_id', sa.Integer(), nullable=True),
    sa.Column('course_project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_project_id'], ['course_project_base.id'], ),
    sa.ForeignKeyConstraint(['user_teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_proj_user_teacher_id'), 'course_proj_user_teacher', ['id'], unique=True)
    op.create_table('stage_course_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('deadline_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_project_id'], ['course_project_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_course_project_id'), 'stage_course_project', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_course_project_id'), table_name='stage_course_project')
    op.drop_table('stage_course_project')
    op.drop_index(op.f('ix_course_proj_user_teacher_id'), table_name='course_proj_user_teacher')
    op.drop_table('course_proj_user_teacher')
    op.drop_index(op.f('ix_course_project_base_id'), table_name='course_project_base')
    op.drop_table('course_project_base')
    # ### end Alembic commands ###
