"""Edit publication table.

Revision ID: 52e95c474c12
Revises: 5d630c810f25
Create Date: 2022-11-08 05:06:14.980021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e95c474c12'
down_revision = '5d630c810f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('publication_type', sa.String(), nullable=False))
    op.alter_column('publications', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('publications', 'publication_type')
    # ### end Alembic commands ###
