"""Add Graduation request

Revision ID: 59f36d9b9219
Revises: 447ed61859ee
Create Date: 2022-11-29 15:00:22.166834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f36d9b9219'
down_revision = '447ed61859ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_graduation_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_student_id', sa.Integer(), nullable=True),
    sa.Column('user_teacher_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_create_graduation_request_id'), 'create_graduation_request', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_create_graduation_request_id'), table_name='create_graduation_request')
    op.drop_table('create_graduation_request')
    # ### end Alembic commands ###
