"""Add count of graduation project for uset_teacher

Revision ID: 8ef8c7994c9b
Revises: c113eb743be9
Create Date: 2022-11-30 18:18:49.285762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef8c7994c9b'
down_revision = 'c113eb743be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count_of_teachers_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_teacher_id', sa.Integer(), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_teacher_id')
    )
    op.create_index(op.f('ix_count_of_teachers_projects_id'), 'count_of_teachers_projects', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_count_of_teachers_projects_id'), table_name='count_of_teachers_projects')
    op.drop_table('count_of_teachers_projects')
    # ### end Alembic commands ###
