"""Add fie_type in files

Revision ID: 92806c5ab827
Revises: c06806220b67
Create Date: 2022-11-02 23:50:50.041706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92806c5ab827'
down_revision = 'c06806220b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_type')
    # ### end Alembic commands ###
