"""fixes v3

Revision ID: a0fb2f94a285
Revises: 
Create Date: 2022-11-19 21:38:43.823828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0fb2f94a285'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_name', sa.String(), nullable=True),
    sa.Column('count_of_hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discipline_name')
    )
    op.create_index(op.f('ix_disciplines_id'), 'disciplines', ['id'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('modification_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('count_of_subgroup', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=True)
    op.create_table('schedule_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_type', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_days_id'), 'schedule_days', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('course_project_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('user_student_id', sa.Integer(), nullable=True),
    sa.Column('percent_of_completion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['user_student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_project_base_id'), 'course_project_base', ['id'], unique=True)
    op.create_table('graduations_project_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_student_id', sa.Integer(), nullable=True),
    sa.Column('pattern_of_education', sa.String(), nullable=False),
    sa.Column('percent_of_completion', sa.Float(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graduations_project_base_id'), 'graduations_project_base', ['id'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_teacher_id', sa.Integer(), nullable=True),
    sa.Column('type_of_lesson', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('schedule_day_id', sa.Integer(), nullable=True),
    sa.Column('subgroup', sa.Integer(), nullable=True),
    sa.Column('cabinet', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['schedule_day_id'], ['schedule_days.id'], ),
    sa.ForeignKeyConstraint(['user_teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=True)
    op.create_table('news_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_posts_id'), 'news_posts', ['id'], unique=True)
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publication_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('user_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_of_studing', sa.DateTime(), nullable=False),
    sa.Column('number_of_ticket', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('subgroup', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_proj_user_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_teacher_id', sa.Integer(), nullable=True),
    sa.Column('course_project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_project_id'], ['course_project_base.id'], ),
    sa.ForeignKeyConstraint(['user_teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_proj_user_teacher_id'), 'course_proj_user_teacher', ['id'], unique=True)
    op.create_table('grad_project_user_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_teacher_id', sa.Integer(), nullable=True),
    sa.Column('graduation_project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['graduation_project_id'], ['graduations_project_base.id'], ),
    sa.ForeignKeyConstraint(['user_teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grad_project_user_teacher_id'), 'grad_project_user_teacher', ['id'], unique=True)
    op.create_table('stage_course_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('deadline_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_project_id'], ['course_project_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_course_project_id'), 'stage_course_project', ['id'], unique=True)
    op.create_table('stage_graduation_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graduation_project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('deadline_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['graduation_project_id'], ['graduations_project_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_graduation_project_id'), 'stage_graduation_project', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_graduation_project_id'), table_name='stage_graduation_project')
    op.drop_table('stage_graduation_project')
    op.drop_index(op.f('ix_stage_course_project_id'), table_name='stage_course_project')
    op.drop_table('stage_course_project')
    op.drop_index(op.f('ix_grad_project_user_teacher_id'), table_name='grad_project_user_teacher')
    op.drop_table('grad_project_user_teacher')
    op.drop_index(op.f('ix_course_proj_user_teacher_id'), table_name='course_proj_user_teacher')
    op.drop_table('course_proj_user_teacher')
    op.drop_table('user_teacher')
    op.drop_table('user_student')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_news_posts_id'), table_name='news_posts')
    op.drop_table('news_posts')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_graduations_project_base_id'), table_name='graduations_project_base')
    op.drop_table('graduations_project_base')
    op.drop_index(op.f('ix_course_project_base_id'), table_name='course_project_base')
    op.drop_table('course_project_base')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schedule_days_id'), table_name='schedule_days')
    op.drop_table('schedule_days')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_disciplines_id'), table_name='disciplines')
    op.drop_table('disciplines')
    # ### end Alembic commands ###
