"""Add rel

Revision ID: a3a75ffabb5e
Revises: 0f39b4586b05
Create Date: 2022-11-08 22:20:06.658013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a75ffabb5e'
down_revision = '0f39b4586b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
