"""Add user in model 

Revision ID: c113eb743be9
Revises: 07af3f3cd9a7
Create Date: 2022-11-30 13:28:37.300006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c113eb743be9'
down_revision = '07af3f3cd9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
